### ISSUE TITLE
When narrow the broswer the navbar collapse doesn't work 

### ISSUE THREAD

**Issue by liu-kanghui** [anlambert/webpack-gulp-es6-angular-express#1] opened 2016-05-17 06:08 UTC
how to fix the problem?  

thanks in advance.

**Comment by anlambert** [comment] 2016-05-17 09:54
Hi Kanghui,

The issue is now fixed in both branches. There was some boostrap scripts and css not loaded so the collapse feature was not working.

Not all bootstrap features are activated by default. You can enable / disable them trough the following file of the project : src/website/bootstrap.config.js.

**Closed by anlambert** 2016-05-17 09:54 UTC

**Comment by liu-kanghui** [comment] 2016-05-18 03:24
Thank you very much !!! 👍
